name: Build and publish grounding_dino

on:
  workflow_dispatch:  # click the button on Github repo!

# There is a single job in this workflow. It's configured to run on the latest available version of Ubuntu.
jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    # Sets the permissions granted to the `GITHUB_TOKEN` for the actions in this job.
    permissions:
      contents: read
      packages: write
      # 
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: publish
        uses: pennsignals/publish_docker-compose@v0.2.5
        with:
          version: 'latest' # optional
          docker_compose: 'label_studio_ml/examples/grounding_dino/docker-compose-build.yml' # required
          repo_token: "${{ secrets.GITHUB_TOKEN }}"


